version: '3'
services:
  reverseproxy:   
     image: nginx
     container_name: reverseproxy
     volumes:                     
       - ./nginx-conf.d:/etc/nginx/conf.d
      
networks:
  default:
    external:
      name: docker_network
