version: '3'
services:
  reverseproxy:   
    image: nginx
    volumes:                     
      - ./nginx-conf.d:/etc/nginx/conf.d
     container_name: reverseproxy
networks:
  default:
    external:
      name: docker_network
